---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-gatsby-starter
  name: test-gatsby-starter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gatsby-starter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: test-gatsby-starter
    spec:
      containers:
      - image: hasura/test-gatsby-starter:bed7c8
        imagePullPolicy: IfNotPresent
        name: test-gatsby-starter
        env:
        - name: GATSBY_ALGOLIA_APP_ID
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: algoliaAppId
        - name: GATSBY_ALGOLIA_SEARCH_KEY
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: algoliaSearchKey
        - name: ALGOLIA_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: algoliaAdminKey
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /graphql/test-gatsby-starter/introduction
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-gatsby-starter
  name: test-gatsby-starter
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-gatsby-starter
  type: ClusterIP
